### ISSUE TITLE
Run checkout of repo

### ISSUE THREAD

**Issue by jassler** [mattfbacon/typst-bot#1]
I cloned the repository, set the Discord key and tried to run the bot using `cargo run`. The program panicked on me however. The `unwrap()` line it panicked on is [here](https://github.com/mattfbacon/typst-bot/blob/af4ba13a3ab6ad9b0c7bd22a654dc2c7dba05ad3/bot/src/bot.rs#L339).

```rust
pub async fn run() {
	let pool = Worker::spawn().unwrap();
	// ...
}
```

The relevant output.

```js
$ cargo run
// ...
     Running `target/debug/typst-bot`
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: spawning worker process.

this is likely because you are trying to run the bot from a checkout of the repo and `worker` is a directory. you can fix this by changing the path to the worker binary to point to the worker binary in the cargo target directory.

Caused by:
    Permission denied (os error 13)', bot/src/bot.rs:339:32
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

<details><summary>Here the entire output.</summary>

```
$ cargo run
    Updating git repository `https://github.com/typst/typst`
  Downloaded async-trait v0.1.68
  Downloaded try-lock v0.2.4
  Downloaded serde-value v0.7.0
  Downloaded derivative v2.2.0
  Downloaded typemap_rev v0.1.5
  Downloaded tokio-macros v2.1.0
  Downloaded sha-1 v0.10.1
  Downloaded futures-sink v0.3.28
  Downloaded ipnet v2.7.2
  Downloaded rustls-pemfile v1.0.2
  Downloaded ordered-float v2.10.0
  Downloaded mime v0.3.17
  Downloaded tokio-rustls v0.23.4
  Downloaded futures-io v0.3.28
  Downloaded hyper-rustls v0.23.2
  Downloaded socket2 v0.4.9
  Downloaded futures-channel v0.3.28
  Downloaded async-tungstenite v0.17.2
  Downloaded tungstenite v0.17.3
  Downloaded futures v0.3.28
  Downloaded tracing v0.1.38
  Downloaded mio v0.8.6
  Downloaded tokio-util v0.7.8
  Downloaded reqwest v0.11.16
  Downloaded hyper v0.14.26
  Downloaded h2 v0.3.18
  Downloaded serenity v0.11.5
  Downloaded tokio v1.28.0
  Downloaded poise_macros v0.5.3
  Downloaded poise v0.5.4
  Downloaded 30 crates (2.6 MB) in 1.30s
   Compiling proc-macro2 v1.0.56
   Compiling quote v1.0.26
   Compiling unicode-ident v1.0.8
   Compiling autocfg v1.1.0
   Compiling cfg-if v1.0.0
   Compiling libc v0.2.142
   Compiling version_check v0.9.4
   Compiling log v0.4.17
   Compiling serde_derive v1.0.160
   Compiling cc v1.0.79
   Compiling serde v1.0.160
   Compiling fnv v1.0.7
   Compiling pin-project-lite v0.2.9
   Compiling futures-core v0.3.28
   Compiling bytes v1.4.0
   Compiling itoa v1.0.6
   Compiling untrusted v0.7.1
   Compiling tokio v1.28.0
   Compiling slab v0.4.8
   Compiling futures-channel v0.3.28
   Compiling memchr v2.5.0
   Compiling futures-sink v0.3.28
   Compiling typenum v1.16.0
   Compiling futures-task v0.3.28
   Compiling ring v0.16.20
   Compiling syn v2.0.15
   Compiling generic-array v0.14.7
   Compiling socket2 v0.4.9
   Compiling mio v0.8.6
   Compiling futures-util v0.3.28
   Compiling once_cell v1.17.1
   Compiling http v0.2.9
   Compiling httparse v1.8.0
   Compiling tinyvec_macros v0.1.1
   Compiling futures-io v0.3.28
   Compiling rustls v0.20.8
   Compiling pin-utils v0.1.0
   Compiling tinyvec v1.6.0
   Compiling tracing-core v0.1.30
   Compiling indexmap v1.9.3
   Compiling unicase v2.6.0
   Compiling percent-encoding v2.2.0
   Compiling syn v1.0.109
   Compiling hashbrown v0.12.3
   Compiling form_urlencoded v1.1.0
   Compiling unicode-normalization v0.1.22
   Compiling getrandom v0.2.9
   Compiling unicode-bidi v0.3.13
   Compiling rand_core v0.6.4
   Compiling crypto-common v0.1.6
   Compiling block-buffer v0.10.4
   Compiling lock_api v0.4.9
   Compiling num-traits v0.2.15
   Compiling thiserror v1.0.40
   Compiling ppv-lite86 v0.2.17
   Compiling idna v0.3.0
   Compiling try-lock v0.2.4
   Compiling parking_lot_core v0.9.7
   Compiling rand_chacha v0.3.1
   Compiling want v0.3.0
   Compiling mime_guess v2.0.4
   Compiling digest v0.10.6
   Compiling http-body v0.4.5
   Compiling cpufeatures v0.2.7
   Compiling httpdate v1.0.2
   Compiling ryu v1.0.13
   Compiling smallvec v1.10.0
   Compiling scopeguard v1.1.0
   Compiling crc32fast v1.3.2
   Compiling ident_case v1.0.1
   Compiling strsim v0.10.0
   Compiling tower-service v0.3.2
   Compiling serde_json v1.0.96
   Compiling webpki v0.22.0
   Compiling sct v0.7.0
   Compiling webpki-roots v0.22.6
   Compiling sha-1 v0.10.1
   Compiling rand v0.8.5
   Compiling base64 v0.21.0
   Compiling base64 v0.13.1
   Compiling async-trait v0.1.68
   Compiling utf-8 v0.7.6
   Compiling mime v0.3.17
   Compiling adler v1.0.2
   Compiling rustversion v1.0.12
   Compiling byteorder v1.4.3
   Compiling miniz_oxide v0.6.2
   Compiling ordered-float v2.10.0
   Compiling rustls-pemfile v1.0.2
   Compiling encoding_rs v0.8.32
   Compiling ipnet v2.7.2
   Compiling serenity v0.11.5
   Compiling time-core v0.1.0
   Compiling flate2 v1.0.25
   Compiling darling_core v0.14.4
   Compiling parking_lot v0.12.1
   Compiling regex-syntax v0.7.1
   Compiling anyhow v1.0.70
   Compiling bitflags v1.3.2
   Compiling typemap_rev v0.1.5
   Compiling tokio-macros v2.1.0
   Compiling futures-macro v0.3.28
   Compiling tracing-attributes v0.1.24
   Compiling thiserror-impl v1.0.40
   Compiling regex v1.8.1
   Compiling darling_macro v0.14.4
   Compiling derivative v2.2.0
   Compiling tracing v0.1.38
   Compiling darling v0.14.4
   Compiling poise_macros v0.5.3
   Compiling futures v0.3.28
   Compiling tokio-util v0.7.8
   Compiling tokio-rustls v0.23.4
   Compiling h2 v0.3.18
   Compiling url v2.3.1
   Compiling serde_urlencoded v0.7.1
   Compiling serde-value v0.7.0
   Compiling dashmap v5.4.0
   Compiling time v0.3.20
   Compiling bincode v1.3.3
   Compiling protocol v0.1.0 (/Users/jassler/Documents/progr/telegram/typst-bot/protocol)
   Compiling tungstenite v0.17.3
   Compiling async-tungstenite v0.17.2
   Compiling hyper v0.14.26
   Compiling hyper-rustls v0.23.2
   Compiling reqwest v0.11.16
   Compiling poise v0.5.4
   Compiling typst-bot v0.1.0 (/Users/jassler/Documents/progr/telegram/typst-bot/bot)
    Finished dev [unoptimized + debuginfo] target(s) in 35.98s
     Running `target/debug/typst-bot`
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: spawning worker process.

this is likely because you are trying to run the bot from a checkout of the repo and `worker` is a directory. you can fix this by changing the path to the worker binary to point to the worker binary in the cargo target directory.

Caused by:
    Permission denied (os error 13)', bot/src/bot.rs:339:32
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

</details>

<details><summary>For completeness' sake, the run output with `RUST_BACKTRACE` set to `1`.</summary>

```
$ RUST_BACKTRACE=1 cargo run  
    Finished dev [unoptimized + debuginfo] target(s) in 0.17s
     Running `target/debug/typst-bot`
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: spawning worker process.

this is likely because you are trying to run the bot from a checkout of the repo and `worker` is a directory. you can fix this by changing the path to the worker binary to point to the worker binary in the cargo target directory.

Caused by:
    Permission denied (os error 13)', bot/src/bot.rs:339:32
stack backtrace:
   0: rust_begin_unwind
             at /rustc/897e37553bba8b42751c67658967889d11ecd120/library/std/src/panicking.rs:584:5
   1: core::panicking::panic_fmt
             at /rustc/897e37553bba8b42751c67658967889d11ecd120/library/core/src/panicking.rs:142:14
   2: core::result::unwrap_failed
             at /rustc/897e37553bba8b42751c67658967889d11ecd120/library/core/src/result.rs:1785:5
   3: core::result::Result<T,E>::unwrap
             at /rustc/897e37553bba8b42751c67658967889d11ecd120/library/core/src/result.rs:1107:23
   4: typst_bot::bot::run::{{closure}}
             at ./bot/src/bot.rs:339:13
   5: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
             at /rustc/897e37553bba8b42751c67658967889d11ecd120/library/core/src/future/mod.rs:91:19
   6: typst_bot::main::{{closure}}
             at ./bot/src/main.rs:26:18
   7: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
             at /rustc/897e37553bba8b42751c67658967889d11ecd120/library/core/src/future/mod.rs:91:19
   8: <core::pin::Pin<P> as core::future::future::Future>::poll
             at /rustc/897e37553bba8b42751c67658967889d11ecd120/library/core/src/future/future.rs:124:9
   9: tokio::runtime::scheduler::current_thread::CoreGuard::block_on::{{closure}}::{{closure}}::{{closure}}
             at /Users/jassler/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.28.0/src/runtime/scheduler/current_thread.rs:541:57
  10: tokio::runtime::coop::with_budget
             at /Users/jassler/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.28.0/src/runtime/coop.rs:107:5
  11: tokio::runtime::coop::budget
             at /Users/jassler/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.28.0/src/runtime/coop.rs:73:5
  12: tokio::runtime::scheduler::current_thread::CoreGuard::block_on::{{closure}}::{{closure}}
             at /Users/jassler/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.28.0/src/runtime/scheduler/current_thread.rs:541:25
  13: tokio::runtime::scheduler::current_thread::Context::enter
             at /Users/jassler/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.28.0/src/runtime/scheduler/current_thread.rs:350:19
  14: tokio::runtime::scheduler::current_thread::CoreGuard::block_on::{{closure}}
             at /Users/jassler/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.28.0/src/runtime/scheduler/current_thread.rs:540:36
  15: tokio::runtime::scheduler::current_thread::CoreGuard::enter::{{closure}}
             at /Users/jassler/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.28.0/src/runtime/scheduler/current_thread.rs:615:57
  16: tokio::macros::scoped_tls::ScopedKey<T>::set
             at /Users/jassler/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.28.0/src/macros/scoped_tls.rs:61:9
  17: tokio::runtime::scheduler::current_thread::CoreGuard::enter
             at /Users/jassler/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.28.0/src/runtime/scheduler/current_thread.rs:615:27
  18: tokio::runtime::scheduler::current_thread::CoreGuard::block_on
             at /Users/jassler/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.28.0/src/runtime/scheduler/current_thread.rs:530:19
  19: tokio::runtime::scheduler::current_thread::CurrentThread::block_on
             at /Users/jassler/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.28.0/src/runtime/scheduler/current_thread.rs:154:24
  20: tokio::runtime::runtime::Runtime::block_on
             at /Users/jassler/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.28.0/src/runtime/runtime.rs:302:47
  21: typst_bot::main
             at ./bot/src/main.rs:26:2
  22: core::ops::function::FnOnce::call_once
             at /rustc/897e37553bba8b42751c67658967889d11ecd120/library/core/src/ops/function.rs:248:5
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
```
</details>

Building seems to work, but not running it. I can't really figure out what the problem is - I know it says to link to the worker binary, but where is it located? How do I link it?

**Comment by mattfbacon** [comment]
Please reference the setup guide in the README.

(I will improve the panic message to suggest that.)

**Comment by jassler** [comment]
Thank you for pointing it out. The setup seems a little foreign to me, however.

1. I `cd`-ed into the `worker` directory and ran `cargo build`, then I `cd ..` back into the root directory.
2. I renamed the `worker` directory to something else, i.e., `worker_dir`.
3. I copy `target/debug/worker` to the root directory. So now the directory tree looks something like this (running `tree -aF`).

```
./
├── Cargo.toml
├── bot/
├── fonts/
├── protocol/
├── target/
│   └── debug/
│       ├── typst-bot*
├── worker*
└── worker_dir/
```

4. Now running `cargo run` works.

While this seems to work, it still seems kinda strange to me the way I have to work with the worker binary. Am I doing it correctly?

**Comment by mattfbacon** [comment]
Sort of. Basically there are two ways to run the bot:

1. From the project directory. This is how you would run it during development. To do this you have to modify the code so that the path to the worker binary points to within your target folder. Then you can run the bot with `cargo build -p worker && cargo run` (to make sure the worker is fresh).
2. In its own deployment. This is how you would run it during production. Just build the two binaries with `cargo build --release --all` (though I suggest building for x86_64-unknown-linux-musl to avoid any dynamic linking incompatibilities), then create the directory structure as described in the README:

```
bot
worker
fonts/
```

Then run `bot` with that directory as the CWD.
This will work with the code as written.

**Comment by mattfbacon** [comment]
Note we will be able to clean this up once https://doc.rust-lang.org/nightly/cargo/reference/unstable.html#artifact-dependencies is stable

**Comment by jassler** [comment]
> the path to the worker binary points to within your target directory

I'm still a little confused what "points to" means in this context - would I actually need to change the code?

I'm sure will get it to run one way or another. Looking forward to when artfact-dependencies becomes stable :P
Thank you for your help!

**Comment by mattfbacon** [comment]
> I'm still a little confused what "points to" means in this context - would I actually need to change the code?

If your target directory is just within the project, then you would have to change the code to make the path be `target/debug/worker`.

**Comment by mattfbacon** [comment]
`cargo metadata --format-version 1 | jq -r .target_directory` will get the target directory. I have considered attempting to discover this within the code but I feel that it's unnecessarily complex.
